spring:
  application:
    name: osg
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MySQLURL}
    username: ${MySQLUSER}
    password: ${MySQLPWD}
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      keepalive-time: 10000
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PWD}
      database: 0     # 使用第几个数据库（0-15）
      lettuce:
        pool:
          max-active: 8   # 连接池最大活跃连接数
          max-idle: 8     # 最大空闲连接
          min-idle: 0     # 最小空闲连接
          max-wait: 100ms # 连接等待超时时间

  ai:
    # 使用通用的 OpenAI 接口配置，指向 DeepSeek/Aliyun/其他厂商
    # 硅基流动 https://api.siliconflow.cn/ SILICONFLOW_API_KEY
    # DeepSeek https://api.deepseek.com DEEPSEEK_API_KEY
    # OFoxAI https://api.ofox.ai/ OFOX_API_KEY
    # KIMI https://api.moonshot.cn/ KIMI_API_KEY
    # 百炼 https://dashscope.aliyuncs.com/compatible-mode/v1 BAILIAN_API_KEY
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        model: claude-opus-4-7
        temperature: 0.1
        top_p: 0.7
        max_tokens: 350000
    openai:
      base-url: https://api.siliconflow.cn/
      api-key: ${SILICONFLOW_API_KEY}
      chat:
        model: ${custom.qwen-name}
        temperature: 0.1
        top_p: 0.7
        frequency_penalty: 0.2
        presence_penalty: 0.1
        max_tokens: 8000
        max-completion-tokens: 2000000
      embedding:
        base-url: https://api.siliconflow.cn/v1
        api-key: ${SILICONFLOW_API_KEY}
        model: ${custom.embedding-name}
        dimensions: 4096
    vectorstore:
      qdrant:
        host: ${QDRANT_URL}
        port: ${QDRANT_PORT}
        api-key: ${QDRANT_API_KEY}
        collection-name: ${QDRANT_COLLECTION_NAME}
        use-tls: false
        initialize-schema: true
    #   vector:
    #     dimensions: 4096
    #     distance-type: COSINE_DISTANCE
    #     index-type: HNSW
    #     initialize-schema: false
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            platform: mysql
    mcp:
      server:
        enabled: true
        name: office-survival-guide
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE
        instructions: 提供天气和 ETF 行情查询工具
        annotation-scanner:
          enabled: true
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        streamable-http:
          mcp-endpoint: /mcp

custom:
  code:
    url: https://api.siliconflow.cn/
    apiKey: ${SILICONFLOW_API_KEY}
    name: Qwen/Qwen3.6-27B #anthropic/claude-opus-4.6 Pro/deepseek-ai/DeepSeek-V3.2 deepseek-v4-flash qwen3-coder-plus
    tokens: 30000
    stop:
      - "```"
      - "```json"
    param:
      temperature: 0.1
      top_p: 0.7
      frequency_penalty: 0.2
      presence_penalty: 0.1
      max_tokens: 30000
      max-completion-tokens: 30000
      enable_thinking: false
  chat:
    url: https://api.siliconflow.cn/
    apiKey: ${SILICONFLOW_API_KEY}
    name: Qwen/Qwen3.6-27B
    tokens: 30000
    stop:
      - "```"
      - "```json"
    param:
      temperature: 0.1
      top_p: 0.7
      frequency_penalty: 0.2
      presence_penalty: 0.1
      max_tokens: 30000
      max-completion-tokens: 30000
      enable_thinking: false
  weather:
    base-url: ${HF_URL}
    api-key: ${HF_KEY}

  mineru-url: ${MINERU_URL}
  mineru-backend: pipeline
  mineru-return_md: false
  return_content_list: true
  return_images: false
  hasGPU: true

  embedding-name: Qwen/Qwen3-Embedding-8B
  rerank-name: Qwen/Qwen3-Reranker-8B
  vl-name: deepseek-ai/DeepSeek-OCR
  maxMessage: 1
  maxToken: 500
  chunkSize: 200

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.ai.transformer.splitter: WARN
    org.apache.pdfbox.rendering:.GlyphCache: OFF
    org.apache.pdfbox.pdmodel.font.PDCIDFontType0: OFF