spring:
  application:
    name: osg
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    pg:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: ${DBURL}
      username: ${DBUSER}
      password: ${DBPWD}
    tidb:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${TiDBURL}
      username: ${TiDBUSER}
      password: ${TiDBPWD}
    hikari:
      max-lifetime: 60000
      idle-timeout: 60000
      keepalive-time: 10000
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PWD}
      database: 0     # 使用第几个数据库（0-15）
      lettuce:
        pool:
          max-active: 8   # 连接池最大活跃连接数
          max-idle: 8     # 最大空闲连接
          min-idle: 0     # 最小空闲连接
          max-wait: 100ms # 连接等待超时时间

  ai:
    # 使用通用的 OpenAI 接口配置，指向 DeepSeek/Aliyun/其他厂商
    # 硅基流动 https://api.siliconflow.cn/ SILICONFLOW_API_KEY
    # DeepSeek https://api.deepseek.com DEEPSEEK_API_KEY
    openai:
      base-url: https://api.siliconflow.cn/
      api-key: ${SILICONFLOW_API_KEY}
      chat:
        options:
          model: ${custom.qwen-name}
          temperature: 0.1
          top_p: 0.7
          stop:
            - "\n"
          frequency_penalty: 0.2
          presence_penalty: 0.1
      embedding:
        base-url: https://api.siliconflow.cn/
        options:
          model: ${custom.embedding-name}
          dimensions: 4096
    vectorstore:
      qdrant:
        host: ${QDRANT_URL}
        port: ${QDRANT_PORT}
        api-key: ${QDRANT_API_KEY}
        collection-name: ${QDRANT_COLLECTION_NAME}
        use-tls: true
        initialize-schema: false
#      pgvector:
#        dimensions: 4096
#        distance-type: COSINE_DISTANCE
#        index-type: HNSW
#        initialize-schema: false
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: never
            platform: mysql

custom:
  coder-name: Qwen/Qwen2.5-Coder-7B-Instruct
  qwen-name: Qwen/Qwen3-8B
  embedding-name: Qwen/Qwen3-Embedding-8B
  rerank-name: Qwen/Qwen3-Reranker-8B
  maxMessage: 1
  maxToken: 500
  chunkSize: 200

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.ai.transformer.splitter: WARN